export enum AuthConstants {
  ACCESS_TOKEN = "SAFEKEY_ACCESS_TOKEN",
  REFRESH_TOKEN = "SAFEKEY_REFRESH_TOKEN",
  ACCESS_USER = "SAFEKEY_ACCESS_USER",
  LOGGED_USER_TYPE = "SAFEKEY_LOGGED_USER_TYPE",
}
